project:
  type: website

website:
  title: "FIT-CLINIC"
  description: "FIT-CLINIC landing page"
  navbar:
    right:
      - text: Home
        href: index.html
      - text: Blog
        href: blog.qmd
